### ISSUE TITLE
Keep track of files processed

### ISSUE THREAD

**Issue by dongbohu** [greenelab/cimr-d#11]
Since the user-submitted yaml file includes md5sum, we can maintain a tab-delimited text file in the repo to keep track of all files that have been successfully downloaded and processed. When a new yaml file is parsed, the parser first reads this tab-delimited file to check whether the request has been processed before or not. If yes, we can either ignore the request silently or generate an error explicitly. Here is the format of the file that I am thinking:

```
file_url                                                        md5sum                             PR#
https://zenodo.org/record/3338180/files/HDL_Cholesterol.txt.gz  2b28816a0a363db1a09ad9a6ba1a6620   123
```
Instead of saving the whole URL, we can track the filename only, because the full URL can be found by the request yml files in PR#.

**Comment by dongbohu** [comment]
Update: @ypar is going to implement a metadata table to fix this issue.

**Comment by ypar** [comment]
This has been addressed by cimr-d_catalog created in [this pr](https://github.com/greenelab/cimr-d/pull/15).
