### ISSUE TITLE
Format of user-submitted YAML file

### ISSUE THREAD

**Issue by dongbohu** [greenelab/cimr-d#17]
The YAML file's format is critical to the success of data processing on our paltform. We need to clearly explain (in `README.md` maybe) which fields are required and which are optional, with sample YAML files to help users get started. 

Also emphasize our preference of putting the download data on Zenodo website.

**Comment by ypar** [comment]
This has been resolved in the past couple of PRs including [this one](https://github.com/greenelab/cimr-d/pull/29)
