### ISSUE TITLE
Avoid duplicate filenames in public "cimr-d" S3 bucket

### ISSUE THREAD

**Issue by ypar** [greenelab/cimr-d#30]
Check existing file list from cimr-d_catalog.txt and call an error if a new PR is filed with the same file_name and data_type

Quote from @dongbohu regarding a potential file_name issue: 
Suppose the output file generated by cimr is going to be data_type/file_name. Before cimr starts writing this file, it should read data_type and file_name columns in cimr-d_catalog.txt to verify that a row of data_type and file_name doesn't exist in cimr-d_catalog.txt. If such a row exists, cimr should report an error and stop immediately; otherwise the file generated will overwrite the file in cimr-d S3 bucket.

**Comment by ypar** [comment]
One potentially useful workaround is creating a temporary ID or some suffix to replace duplicate names as long as hash differs. This seems like an important issue to address immediately with better solutions to come when more edge cases are discussed and tested.

**Comment by dongbohu** [comment]
Whether this issue should be in `cimr` or `cimr-d` depends on when we should report this error.

Since `cimr-d` simply calls `cimr` command with an input yml file, `cimr-d` can only report the error AFTER the data processing is done and BEFORE copying the output file to S3. It will be a waste of time for both users and CircleCI.

On the other hand, we can report this error inside `cimr` after the file is downloaded but before data processing starts. That was why I added the issue in `cimr`.

**Comment by ypar** [comment]
Incorrect. cimr-d checks the yaml file before calling cimr using [shyaml](https://github.com/greenelab/cimr-d/blob/master/.circleci/handle_request.sh). 

There really isn't a benefit of having cimr check for duplicates as it is just a general purpose tool. I could insert an arbitrary timestamp or some shifting suffix when duplicate file names are found. However, I have not decided whether that is necessary for cimr while it is essential for cimr-d to prevent overwriting.

**Comment by ypar** [comment]
I suspect a non-trivial number of contributors will have files with really generic and meaningless names like plink.assoc or names based on a common scheme (e.g. bmi_gwas.txt.gz, which can be any of >10 different cohorts that independently performed a bmi gwas).

Eventually, I will integrate more complex checking system based on the content of the file but file name + hash check will do for now.

**Comment by dongbohu** [comment]
`cimr-d` checks the md5sum in yaml because the yaml file is `cimr-d`'s input. Without de-archiving the downloaded file (which is done inside `cimr`), how can it check the possible duplicate of output files?

**Comment by ypar** [comment]
I see what you mean. It can extract the file name from the url but it does need some tweaking. I will address this in my next pr.

**Comment by dongbohu** [comment]
Using the md5sum hash as a suffix of output file is one solution, but the hash includes 32 characters, which will make the output filenames long (and ugly). We could use less characters from the hash, but then they won't guarantee the uniqueness. Adding something like `PR-n` might be better.

**Comment by ypar** [comment]
Yeah, that makes sense.

**Comment by dongbohu** [comment]
Fixed by PR #33.
