### ISSUE TITLE
commits in processed directory not allowed

### ISSUE THREAD

**Issue by ypar** [greenelab/cimr-d#47]
We have discussed that we need to set some boundaries to prevent accidental deletion of cimr-d data, including those in the processed dir. However, I am frequently running into issues when I am processing two PRs simultaneously, for instance. And the processed dir commit error is called by not having the master branch of the local submitter (me on a different branch in this case) matching the github master branch. 

It will be useful to reduce this error to just ignore commits to such directories (or overwrite with the most recent master) rather than sys.exit as a default.

**Comment by dongbohu** [comment]
Fixed by #52.
