### ISSUE TITLE
cimr-d version number in S3 bucket filenames

### ISSUE THREAD

**Issue by dongbohu** [greenelab/cimr-d#954]
During the discussion on 10/17/2019 with @cgreene and @ypar, we decided to add a cimr-d version number to each output filename that are saved in the public S3 bucket to keep track of cimr-d data processing.

**Comment by ypar** [comment]
this issue has been deprecated. As of cimr v.0.1.7 processing of cimr-d release 1.0:

* cimr-d catalog.txt contains the version number of cimr software used for processing. 
* cimr-d output filenames contain cimr-d PR numbers representative of the file submission.
